### ISSUE TITLE
Nginx: Lemmy can be accessed through ip address

### ISSUE THREAD

**Issue by anmol26s** [LemmyNet/lemmy#1430]
Found a bug? Please fill out the sections below. 👍

For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Issue Summary

I followed the documentation here: https://join.lemmy.ml/docs/en/administration/install_docker.html
The Nginx configuration is same as here: https://raw.githubusercontent.com/LemmyNet/lemmy/main/ansible/templates/nginx.conf
Only I am trying to use 127.0.0.1 instead of 0.0.0.0.
It works if I am binding 0.0.0.0 as it should be but not with 127.0.0.1.
But on 0.0.0.0, Lemmy can be accessed by the IP:port. As a normal instance this would not be desired.

### Steps to Reproduce
Eg. http://lemmy.161.social/ can be accessed by its IP http://135.181.85.165:1235/

**Comment by anmol26s** [comment]
Here two other instances.
http://88.99.147.159:1235/
http://51.77.211.95:1235/

**Comment by dessalines** [comment]
That's bypassing the nginx entirely, my guess is that their docker-compose.yml files aren't using `"127.0.0.1:8536:8536"`, for the ports, but I can't be certain, as I don't have their docker-compose.yml files.

**Comment by dessalines** [comment]
Oh I see yeah this is probably the issue:

```
  lemmy-ui:
    image: dessalines/lemmy-ui:0.9.7
    ports:
      - "1235:1234"
```

Check out ports for the other ones. I can fix this soon.

But also I'd recommend for a production server, using the ansible, and not the docker install.

**Comment by anmol26s** [comment]
The docker-compose.yml looks like this.

```
version: '2.2'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  lemmy:
    image: dessalines/lemmy:0.9.7
    ports:
      - "127.0.0.1:8536:8536"
    restart: always
    environment:
      - RUST_LOG=error
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs
      - iframely

  lemmy-ui:
    image: dessalines/lemmy-ui:0.9.7
    ports:
      - "1235:1234"
    restart: always
    environment:
      - LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_EXTERNAL_HOST=127.0.0.1:8536
      - LEMMY_HTTPS=true
    depends_on: 
      - lemmy

  pictrs:
    image: asonix/pictrs:v0.2.5-r0
    ports: 
      - "127.0.0.1:8537:8080"
    user: 991:991
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always

  iframely:
    image: dogbin/iframely:latest
    ports:
      - "127.0.0.1:8061:80"
    volumes:
      - ./iframely.config.local.js:/iframely/config.local.js:ro
    restart: always
    mem_limit: 100m

```
I am trying to package Lemmy for Yunohost. And there this would  be a security issue. It would be helpful if this can be patched.
