### ISSUE TITLE
Traefik and pict-rs difficulty

### ISSUE THREAD

**Issue by vinodjam** [LemmyNet/lemmy#1443]
Hi,

I've been trying to run lemmy with traefik as the reverse proxy. I've been able to do the normal stuff like creating posts but not yet been able to get images working yet. In the example nginx config I found 1 relevant line regarding pictrs(location ~ ^/(api|pictrs|feeds|nodeinfo|.well-known)) which I think I've replicated in traefik's format.  It could easily be some silly mistake on my part but I hope you could help me in understanding how pictrs works with lemmy and how I could get more useful debug info. As an example, some output when I try to upload an avatar is given below. Also note that there is no file created in volume/pictrs/files. Thank you for your help in advance

In the browser console
```
GET https://DOMAIN.com/pictrs/image/thNncitjY5.png
[HTTP/2 500 Internal Server Error 57ms] 
```
Some relevant lines from docker logs
```
lemmy       | [2021-02-20T06:20:08Z INFO  actix_web::middleware::logger] 172.25.0.32:52310 "POST /pictrs/image HTTP/1.1" 201 76 "https://DOMAIN.com/u/USER" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0" 0.048148
lemmy       | [2021-02-20T06:20:08Z INFO  actix_web::middleware::logger] 172.25.0.32:52310 "GET /pictrs/image/thNncitjY5.png HTTP/1.1" 200 3118 "https://DOMAIN.com/u/USER" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0" 0.002617

pictrs_1    | Feb 20 06:20:08.887  INFO actix_web::middleware::logger: 172.30.0.4:54694 "POST /image HTTP/1.1" 201 73 "https://DOMAIN.com/u/USER" "pict-rs-frontend, v0.1.0" 0.039379
pictrs_1    | Feb 20 06:20:08.991  INFO actix_web::middleware::logger: 172.30.0.4:54694 "GET /image/original/thNncitjY5.png HTTP/1.1" 200 3118 "https://DOMAIN.com/u/USER" "pict-rs-frontend, v0.1.0" 0.001208
```
My docker-compose file is given below
```
version: '2.2'

services:
  postgres:
    image: postgres:12-alpine
    container_name: lemmy_postgres
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always
    expose:
      - 5432
    networks:
      - lemmy

  lemmy:
    image: dessalines/lemmy:0.9.9
    container_name: lemmy
    expose:
      - 8536
    restart: always
    environment:
      - RUST_LOG=info
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs
      - iframely
    networks:
      - lemmy
      - net
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.lemmy.rule=(Host(`DOMAIN.com`) && (PathPrefix(`/pictrs`) || PathPrefix(`/api`) || PathPrefix(`/feeds`)  || PathPrefix(`/nodeinfo`) || PathPrefix(`/.well-known`))) || (Host(`DOMAIN.com`) && Method(`POST`)) || (Host(`DOMAIN.com`) && Headers(`Content-Type`, `application/activity+json`)) || (Host(`DOMAIN.com`) && Headers(`Content-Type`, `application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"`))'
      - 'traefik.http.routers.lemmy.entrypoints=https'
      - 'traefik.http.routers.lemmy.tls=true'
      - 'traefik.http.routers.lemmy.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.lemmy.middlewares=authelia@docker'
      - 'traefik.docker.network=net'
      - 'traefik.http.services.lemmy.loadbalancer.server.port=8536'

  lemmy-ui:
    image: dessalines/lemmy-ui:0.9.9
    container_name: lemmy-ui
    expose:
      - 1234
    restart: always
    environment:
      - LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_EXTERNAL_HOST=DOMAIN.com
      - LEMMY_HTTPS=false
    depends_on:
      - lemmy
    networks:
      - lemmy
      - net
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.lemmy-ui.rule=Host(`DOMAIN.com`)'
      - 'traefik.http.routers.lemmy-ui.entrypoints=https'
      - 'traefik.http.routers.lemmy-ui.tls=true'
      - 'traefik.http.routers.lemmy-ui.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.lemmy-ui.middlewares=authelia@docker'
      - 'traefik.docker.network=net'
      - "traefik.http.services.lemmy-ui.loadbalancer.server.port=1234"

  pictrs:
    image: asonix/pictrs:v0.2.5-r0
    container_name: lemmy_pictrs
    expose:
      - 8080
    user: 991:991
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always
    networks:
      - lemmy

  iframely:
    image: dogbin/iframely:latest
    container_name: lemmy_iframely
    expose:
      - 8061
    volumes:
      - ./iframely.config.local.js:/iframely/config.local.js:ro
    restart: always
    mem_limit: 100m
    networks:
      - lemmy
      - net
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.lemmy_iframely.rule=Host(`DOMAIN.com`) && PathPrefix(`/iframely`)'
      - 'traefik.http.routers.lemmy_iframely.entrypoints=https'
      - 'traefik.http.routers.lemmy_iframely.tls=true'
      - 'traefik.http.routers.lemmy_iframely.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.lemmy_iframely.middlewares=authelia@docker'
      - 'traefik.docker.network=net'
      - 'traefik.http.services.lemmy_iframely.loadbalancer.server.port=8061'

networks:
  net:
    external: true
  lemmy:
```
