### ISSUE TITLE
invalid type: string "tcp://10.128.35.190:8080", expected an integer for key `port` in the environment

### ISSUE THREAD

**Issue by stemid** [LemmyNet/lemmy#1519]
thread 'main' panicked at 'invalid type: string "tcp://10.128.35.190:8080", expected an integer for key `port` in the environment', crates/utils/src/settings.rs:82:15

I'm trying to deploy Lemmy to kubernetes and getting this error in the lemmy container.

Here is its Deployment manifest and its hjson file. I'm not sure which port this error is referring to.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lemmy
  name: lemmy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lemmy
  template:
    metadata:
      labels:
        app: lemmy
    spec:
      containers:
      - env:
        - name: RUST_LOG
          value: debug
        - name: RUST_BACKTRACE
          value: full
        image: docker.io/dessalines/lemmy:0.9.9
        name: lemmy
        ports:
        - containerPort: 8536
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        volumeMounts:
        - mountPath: /config/config.hjson
          name: lemmy-config
          subPath: lemmy.hjson
      - env:
        - name: LEMMY_INTERNAL_HOST
          value: lemmy:8080
        - name: LEMMY_EXTERNAL_HOST
          value: api.lemlar.se
        - name: LEMMY_HTTPS
          value: "true"
        image: docker.io/dessalines/lemmy-ui:0.9.9
        name: lemmy-ui
        ports:
        - containerPort: 8536
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
      - image: docker.io/dogbin/iframely:latest
        name: iframely
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /iframely/config.local.js
          name: lemmy-config
          subPath: iframely.config.local.js
      - image: docker.io/asonix/pictrs:v0.2.6-r1
        name: pictrs
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /mnt
          name: pictrs-data
      volumes:
      - name: lemmy-config
        secret:
          secretName: lemmy-config-88m269d7t6
      - name: pictrs-data
        persistentVolumeClaim:
          claimName: pvc-pictrs01
```

```hjson
{
  # for more info about the config, check out the documentation
  # https://join.lemmy.ml/docs/en/administration/configuration.html

  setup: {
    # username for the admin user
    admin_username: "secret"
    # password for the admin user
    admin_password: "secret"
    # name of the site (can be changed later)
    site_name: "lemlar"
  }

  # the domain name of your instance (eg "lemmy.ml")
  hostname: "lemlar.se"
  # address where lemmy should listen for incoming requests
  bind: "0.0.0.0"
  # port where lemmy should listen for incoming requests
  port: 8536
  # json web token for authorization between server and client
  jwt_secret: "secret"

  pictrs_url: "http://localhost:8080"
  iframely_url: "http://localhost:80"

  # settings related to the postgresql database
  database: {
    # name of the postgres database for lemmy
    database: "secret"
    # username to connect to postgres
    user: "secret"
    # password to connect to postgres
    password: "secret"
    # host where postgres is running
    host: "secret"
    # port where postgres can be accessed
    port: 5432
    # maximum number of active sql connections
    pool_size: 5
  }
#  # optional: email sending configuration
#  email: {
#    # hostname and port of the smtp server
#    smtp_server: ""
#    # login name for smtp server
#    smtp_login: ""
#    # password to login to the smtp server
#    smtp_password: ""
#    # address to send emails from, eg "noreply@your-instance.com"
#    smtp_from_address: ""
#    # whether or not smtp connections should use tls
#    use_tls: true
#  }
}
```

**Comment by Nutomic** [comment]
Sorry, we dont know anything about Kubernetes and dont support it as an installation method, so we cant help you.

**Comment by stemid** [comment]
Just for future reference, I resolved this by setting two environment variables.

```yaml
      containers:
        - name: lemmy
          env:
            - name: LEMMY_PORT
              value: "8536"
            - name: LEMMY_DATABASE__PORT
              value: "5432"
```
