### ISSUE TITLE
Federation lemmy image causes lemmy-ui to receive incorrect JSON that it cannot parse

### ISSUE THREAD

**Issue by HorseJump** [LemmyNet/lemmy#1689]
Found a bug? Please fill out the sections below. 👍

For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Issue Summary

504 gateway error occurs when lemmy is deployed with the lemmy:federation image. This does not occur with the 0.11.3 image.

### Technical details

docker-compose and logs
docker-compose.yml
```
version: '2.2'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  lemmy:
    image: dessalines/lemmy:federation
    ports:
      - "127.0.0.1:8536:8536"
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_queries=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs
      - iframely

  lemmy-ui:
    image: dessalines/lemmy-ui:0.11.3
    ports:
      - "127.0.0.1:1235:1234"
    restart: always
    environment:
      - LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_EXTERNAL_HOST=localhost:8536
      - LEMMY_HTTPS=false
    depends_on:
      - lemmy

  pictrs:
    image: asonix/pictrs:v0.2.6-r2
    ports:
      - "127.0.0.1:8537:8080"
    user: 991:991
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always

  iframely:
    image: dogbin/iframely:latest
    ports:
      - "127.0.0.1:8061:80"
    volumes:
      - ./iframely.config.local.js:/iframely/config.local.js:ro
    restart: always
    mem_limit: 200m
```

`sudo docker-compose logs lemmy`
```
Attaching to lemmy_lemmy_1
lemmy_1     | warning: invalid logging spec 'info"', ignoring it
lemmy_1     | [2021-08-04T22:09:14Z INFO  lemmy_server::db::code_migrations] Running user_updates_2020_04_02
lemmy_1     | [2021-08-04T22:09:14Z INFO  lemmy_server::db::code_migrations] 0 user rows updated.
lemmy_1     | [2021-08-04T22:09:14Z INFO  lemmy_server::db::code_migrations] Running community_updates_2020_04_02
lemmy_1     | [2021-08-04T22:09:14Z INFO  lemmy_server::db::code_migrations] 0 community rows updated.
lemmy_1     | [2021-08-04T22:09:14Z INFO  lemmy_server::db::code_migrations] Running post_updates_2020_04_03
lemmy_1     | [2021-08-04T22:09:14Z INFO  lemmy_server::db::code_migrations] 0 post rows updated.
lemmy_1     | [2021-08-04T22:09:14Z INFO  lemmy_server::db::code_migrations] Running comment_updates_2020_04_03
lemmy_1     | [2021-08-04T22:09:14Z INFO  lemmy_server::db::code_migrations] 0 comment rows updated.
lemmy_1     | [2021-08-04T22:09:14Z INFO  lemmy_server::db::code_migrations] Running private_message_updates_2020_05_05
lemmy_1     | [2021-08-04T22:09:14Z INFO  lemmy_server::db::code_migrations] 0 private message rows updated.
lemmy_1     | Starting http server at 0.0.0.0:8536
lemmy_1     | federation enabled, host is midwest.social
```
`sudo docker-compose logs lemmy-ui`
```
lemmy-ui_1  | Inferno is in development mode.
lemmy-ui_1  | Inferno is in development mode.
lemmy-ui_1  | Inferno is in development mode.
lemmy-ui_1  | httpbase: http://lemmy:8536
lemmy-ui_1  | wsUri: ws://lemmy:8536/api/v3/ws
lemmy-ui_1  | No JWT cookie found.
lemmy-ui_1  | http://0.0.0.0:1234
lemmy-ui_1  | (node:1) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://lemmy:8536/api/v3/site? reason: Unexpected end of JSON input
lemmy-ui_1  |     at /app/node_modules/node-fetch/lib/index.js:272:32
lemmy-ui_1  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
lemmy-ui_1  | (Use `node --trace-warnings ...` to show where the warning was created)
lemmy-ui_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
lemmy-ui_1  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
lemmy-ui_1  | (node:1) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://lemmy:8536/api/v3/site? reason: Unexpected end of JSON input
lemmy-ui_1  |     at /app/node_modules/node-fetch/lib/index.js:272:32
lemmy-ui_1  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
lemmy-ui_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
lemmy-ui_1  | (node:1) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://lemmy:8536/api/v3/site? reason: Unexpected end of JSON input
lemmy-ui_1  |     at /app/node_modules/node-fetch/lib/index.js:272:32
lemmy-ui_1  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
lemmy-ui_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
```

* What OS are you trying to install lemmy on? 
Ubuntu 20.04 LTS
