### ISSUE TITLE
Mastodon federation not possible

### ISSUE THREAD

**Issue by kromonos** [LemmyNet/lemmy#1909]
I've tried from social.snopyta.org, writing.exchange, and Anoxinon Mastodon. It's possible to find `@lemmy@lemmy.ml` but not `@bkali@fapsi.be` or `@house_of_teleyal@fapsi.be`.

I can't find any fail entries in the log file. 

lemmy.hjson:  
```hjson
{
  hostname: "fapsi.be"
  bind: "0.0.0.0"
  port: 8536
  jwt_secret: ""
  pictrs_url: "http://pictrs:8080"
  actor_name_max_length: 32

  database: {
    database: ""
    user: ""
    password: ""
    host: ""
    port: 5432
    pool_size: 5
  }

  rate_limit: {
    message: 180
    message_per_second: 60
    post: 6
    post_per_second: 600
    register: 3
    register_per_second: 3600
    image: 6
    image_per_second: 3600
  }

  federation: {
    enabled: true
    #allowed_instances: [ "lemmy.ml", "sopuli.xyz" ]
    #blocked_instances: [ ]
    #strict_allowlist: false
  }

  captcha: {
    enabled: true
    difficulty: medium # Can be easy, medium, or hard
  }

  email: {
    smtp_server: ""
    smtp_login: ""
    smtp_password: ""
    smtp_from_address: ""
    use_tls: true
  }

  slur_filter:
    '''
    (fag(g|got|tard)?\b|cock\s?sucker(s|ing)?|ni((g{2,}|q)+|[gq]{2,})[e3r]+(s|z)?|mudslime?s?|\bspi(c|k)s?\b|\bchinks?|gooks?|whor(es?|ing)|\btr(a|@)nn?(y|ies?)|\b(b|re|r)tard(ed)?s?|gabapin|tapentadol|erospharmacy|aspadol|cenforce|vashikaran|(cash(\s|\-|_)?app)|frenoneart|redkoi89|slauka|naarielart|EvieeChan|Arysae|sylessae|Lacrima(Art)?|DeaLun(Art)?|wnike(artist)?|GisellePaints|Nozomi((_)?Mats)?|Rosennia(Art)?s?|(The)?Mandii|Basilisk(_Art)?|CylHighblossom|Celestial(Fang|commission|art)|lizbeth(490021)?|OffbeatWorlds|wildcharge(art)?|ammatice|waschbaerella|(This(Is)?)?Radinsky|Yorugami|midorisa|level20Artist|AskMischi|viimorte|nalou(_|\-|\s)arts?|indii?creates|arhiee(art)?|themorrigans(art)?|LagerdahlPhoto|cabslogyt|ophelianoir|hiduranpdm|cince\.arts|offbeatworlds|artmmkay|GianaraArt|thisisradinsky|karinkabogucka|jeleynai|e_maria|joan\.culum|magicalscope(art)?|onyrica|pastoutlander|othalam|indicreatesbusiness|june\.jenssen|angelis|solinii|delsdoodlesart|mastoart|delsdoodles|vajgand|dona@duck\.com|ottiliathouvenin|rachelmcewan(art)?|afferton(art)?|gracezhu(art)?|ariannaclimaci|Trooberger|ThisIsTroo|HeyItsAraas|peshiko(\.art)?|slime\.global|galders?(\-|\s|_|)?(art)?|tindomiel|LenoreLandry|(Tin)?Silverthorn|surenlicious(art)?|Lenamo(\.)?art|hackers\.town|wxcafe\.net|weirder\.earth|tenforward\.social|fuk\.re|rage\.love|eso\-rollenspiel\.de|mastodonten\.de|mastodon\.art|onyrica\.art|sylessae\.art|MicheleQuirke|pikabloo|JuliaMetzger(Art)?|LeraPI(_LP)?|Aleriia(_V)?|Loftsteinn|Elbenherz(Art)?|artelsia|enia(art)?|Rgdraw|SmugGoat|(The)?KrakensMark|Tales\sof\sthe\sKnight|Nithclipse|anesvalt(\-|_)(art)?|wolve(\-|_)rain|pinxiedust|DrewWinchester|Arasteia(Art)?|maiderbee|Luneiress|shadowsparkpub\.com|authormccorkle\.com|silverthorn\.house|CherRo(_|\-|\.)Art|vicevans137|PatrickMcCabe(AC)?|nippaaah|raekomi{1,3}|shargon|instagram\.com|RosyHaven|MusketsGoBoom|Meramii_|cgmythology|feedyourgames|adamasnemesis(\.com)?|RedVeril|Heylookapanda|EvyPark(Art)?|Marcel(_|\-|\s|\.)?Hampel|rin(_|\-|\s|\.)?meraki|SAGAUart)
    '''
}
```

I also tried without blacklist and without slur filter. But the result is the same.  

docker-compose.yaml:  
```
version: '2.2'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  lemmy:
    image: dessalines/lemmy:0.14.0
    ports:
      - "192.168.8.3:8536:8536"
    restart: always
    environment:
        - TZ="Europe/Berlin"
        - RUST_LOG="debug,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_apub_receive=info,lemmy_db_queries=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"
        - NODE_TLS_REJECT_UNAUTHORIZED="0"
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs
      - iframely

  lemmy-ui:
    image: dessalines/lemmy-ui:0.14.0
    ports:
      - "192.168.8.3:1235:1234"
    restart: always
    environment:
      - TZ="Europe/Berlin"
      - LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_EXTERNAL_HOST=localhost:8536
      - LEMMY_HTTPS=false
    depends_on: 
      - lemmy

  pictrs:
    image: asonix/pictrs:v0.2.6-r1
    ports: 
      - "192.168.8.3:8537:8080"
    user: 991:991
    environment:
      - RUST_LOG="debug"
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always

  iframely:
    image: dogbin/iframely:latest
      #image: kfei/iframely:develop
    ports:
      - "8061:80"
    volumes:
      - ./iframely.config.local.js:/iframely/config.local.js:ro
      - ./volumes/whitelist:/iframely/whitelist
    restart: always
    mem_limit: 200m
    entrypoint:
      - node
      - server
      - -v
```

```nginx
upstream lemmy {
    server "192.168.8.3:8536";
}

upstream lemmy-ui {
    server "192.168.8.3:1235";
}

server {
    listen 80;
    listen [::]:80;
    server_name fapsi.be;
    include /etc/nginx/letsencrypt.conf;
    access_log off;

    return 301 https://fapsi.be$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name fapsi.be;

    access_log off;

    include /etc/nginx/letsencrypt.conf;
    
    ssl_certificate /acme/fapsi.be/fullchain.cer;
    ssl_certificate_key /acme/fapsi.be/fapsi.be.key;
    ssl_trusted_certificate /acme/fapsi.be/fullchain.cer;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
    ssl_session_timeout  10m;

    server_tokens off;

    gzip on;
    gzip_types text/css application/javascript image/svg+xml;
    gzip_vary on;

    add_header Strict-Transport-Security "max-age=63072000";
    add_header Referrer-Policy "same-origin";
    add_header X-Content-Type-Options "nosniff";
    add_header X-Frame-Options "DENY";
    add_header X-XSS-Protection "1; mode=block";

    client_max_body_size 20M;
    ignore_invalid_headers off;
    proxy_buffering off;

    # frontend
    location / {
      set $proxpass "http://lemmy-ui";
      if ($http_accept = "application/activity+json") {
        set $proxpass "http://lemmy";
      }
      if ($http_accept = "application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"") {
        set $proxpass "http://lemmy";
      }
      if ($request_method = POST) {
        set $proxpass "http://lemmy";
      }
      proxy_pass $proxpass;

      rewrite ^(.+)/+$ $1 permanent;

      # Send actual client IP upstream
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_read_timeout 90;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_request_buffering off; # Disable any internal request bufferring.
    }

    # backend
    location ~ ^/(api|pictrs|feeds|nodeinfo|.well-known) {
      proxy_pass http://192.168.8.3:8536;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      # Add IP forwarding headers
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }


    # Redirect pictshare images to pictrs
    location ~ /pictshare/(.*)$ {
      return 301 /pictrs/image/$1;
    }
}
```

But there is sometimes an error in the logfiles, which causes the lemmy-ui to restart:
```
lemmy-ui_1  | /app/node_modules/node-fetch/lib/index.js:272
lemmy-ui_1  | 				return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
lemmy-ui_1  | 				                           ^
lemmy-ui_1  | FetchError: invalid json response body at http://lemmy:8536/api/v3/user?sort=New&saved_only=false&page=1&limit=20&username=VonMax%40lemmy.ml reason: Unexpected token E in JSON at position 0
lemmy-ui_1  |     at /app/node_modules/node-fetch/lib/index.js:272:32
lemmy-ui_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
lemmy-ui_1  |     at async Promise.all (index 0) {
lemmy-ui_1  |   type: 'invalid-json'
lemmy-ui_1  | }
```
