### ISSUE TITLE
400 Error on any image upload

### ISSUE THREAD

**Issue by Phlogi** [LemmyNet/lemmy#2403]
### Issue Summary

Uploading any image (e.g. avatar on admin settings) causes a 400 error: 
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/6451003/184555957-28cb260d-93d6-4432-8a35-a235095b21a4.png">

Error in frontend bottom left:
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

### Steps to Reproduce

1. Login
2. Upload avatar image

#### docker logs
<details>
  <summary>Click to open</summary>

```docker-compose down; docker-compose up --remove-orphans
Removing hs1test_nginx_1    ... done
Removing hs1test_lemmy-ui_1 ... done
Removing hs1test_lemmy_1    ... done
Removing hs1test_postgres_1 ... done
Removing hs1test_pictrs_1   ... done
Removing network hs1test_default
Creating network "hs1test_default" with the default driver
Creating hs1test_pictrs_1   ... done
Creating hs1test_postgres_1 ... done
Creating hs1test_lemmy_1    ... done
Creating hs1test_lemmy-ui_1 ... done
Creating hs1test_nginx_1    ... done
Attaching to hs1test_pictrs_1, hs1test_postgres_1, hs1test_lemmy_1, hs1test_lemmy-ui_1, hs1test_nginx_1
lemmy-ui_1  | Inferno is in development mode.
lemmy_1     | Starting http server at 0.0.0.0:8536
nginx_1     | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_1     | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
lemmy-ui_1  | httpbase: http://lemmy:8536
lemmy-ui_1  | wsUri: ws://lemmy:8536/api/v3/ws
lemmy-ui_1  | isHttps: false
pictrs_1    | 2022-08-14T21:08:47.242766Z DEBUG sled::pagecache::iterator: ordering before clearing tears: {0: 0}, max_header_stable_lsn: 0
pictrs_1    | 2022-08-14T21:08:47.242856Z DEBUG sled::pagecache::iterator: in clean_tail_tears, found missing item in tail: None and we'll scan segments {0: 0} above lowest lsn 0
pictrs_1    | 2022-08-14T21:08:47.243149Z DEBUG sled::pagecache::iterator: filtering out segments after detected tear at (lsn, lid) 775
pictrs_1    | 2022-08-14T21:08:47.243412Z DEBUG sled::pagecache::iterator: hit max_lsn 775 in iterator, stopping
pictrs_1    | 2022-08-14T21:08:47.243420Z DEBUG sled::pagecache::snapshot: zeroing the end of the recovered segment at lsn 0 between lids 776 and 524287
pictrs_1    | 2022-08-14T21:08:47.243626Z DEBUG sled::pagecache::blob_io: gc_blobs removing any blob with an lsn above 776
pictrs_1    | 2022-08-14T21:08:47.243745Z DEBUG sled::pagecache::segment: SA starting with tip 524288 stable -1 free {}
pictrs_1    | 2022-08-14T21:08:47.243750Z DEBUG sled::pagecache::iobuf: starting log at recovered active offset 776, recovered lsn 776
pictrs_1    | 2022-08-14T21:08:47.243753Z DEBUG sled::pagecache::iobuf: starting IoBufs with next_lsn: 776 next_lid: 776
pictrs_1    | 2022-08-14T21:08:47.243759Z DEBUG sled::pagecache: load_snapshot loading pages from 0..18
lemmy-ui_1  | No JWT cookie found.
pictrs_1    | 2022-08-14T21:08:47.244078Z DEBUG sled::pagecache::logger: IoBufs dropped
nginx_1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
pictrs_1    | 2022-08-14T21:08:47.244305Z DEBUG sled::pagecache::iterator: ordering before clearing tears: {0: 0}, max_header_stable_lsn: 0
pictrs_1    | 2022-08-14T21:08:47.244314Z DEBUG sled::pagecache::iterator: in clean_tail_tears, found missing item in tail: None and we'll scan segments {0: 0} above lowest lsn 0
pictrs_1    | 2022-08-14T21:08:47.244519Z DEBUG sled::pagecache::iterator: filtering out segments after detected tear at (lsn, lid) 775
pictrs_1    | 2022-08-14T21:08:47.244735Z DEBUG sled::pagecache::iterator: hit max_lsn 775 in iterator, stopping
pictrs_1    | 2022-08-14T21:08:47.244749Z DEBUG sled::pagecache::snapshot: zeroing the end of the recovered segment at lsn 0 between lids 776 and 524287
pictrs_1    | 2022-08-14T21:08:47.244906Z DEBUG sled::pagecache::blob_io: gc_blobs removing any blob with an lsn above 776
pictrs_1    | 2022-08-14T21:08:47.244953Z DEBUG sled::pagecache::segment: SA starting with tip 524288 stable -1 free {}
pictrs_1    | 2022-08-14T21:08:47.244957Z DEBUG sled::pagecache::iobuf: starting log at recovered active offset 776, recovered lsn 776
pictrs_1    | 2022-08-14T21:08:47.244960Z DEBUG sled::pagecache::iobuf: starting IoBufs with next_lsn: 776 next_lid: 776
pictrs_1    | 2022-08-14T21:08:47.244965Z DEBUG sled::pagecache: load_snapshot loading pages from 0..18
pictrs_1    | 2022-08-14T21:08:47.245094Z  INFO restructure{store=FileStore { path_gen: "generator", root_dir: "/mnt" }}: pict_rs::store::file_store::restructure: new
pictrs_1    | 2022-08-14T21:08:47.245119Z  INFO restructure{store=FileStore { path_gen: "generator", root_dir: "/mnt" }}: pict_rs::store::file_store::restructure: close time.busy=10.2µs time.idle=15.2µs
pictrs_1    | 2022-08-14T21:08:47.245362Z  INFO actix_server::builder: Starting 4 workers
pictrs_1    | 2022-08-14T21:08:47.245978Z  INFO actix_server::server: Actix runtime found; starting in Actix runtime
lemmy-ui_1  | http://0.0.0.0:1234
postgres_1  |
postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  |
nginx_1     | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
postgres_1  | 2022-08-14 21:08:47.286 UTC [1] LOG:  starting PostgreSQL 14.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, 64-bit
postgres_1  | 2022-08-14 21:08:47.287 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2022-08-14 21:08:47.287 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2022-08-14 21:08:47.290 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2022-08-14 21:08:47.293 UTC [21] LOG:  database system was shut down at 2022-08-14 21:06:40 UTC
postgres_1  | 2022-08-14 21:08:47.296 UTC [1] LOG:  database system is ready to accept connections
nginx_1     | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx_1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx_1     | /docker-entrypoint.sh: Configuration complete; ready for start up```
```
</details>

#### Nginx request log
```
nginx_1     | 192.168.1.12 - - [14/Aug/2022:21:41:09 +0000] "POST /pictrs/image HTTP/1.1" 400 15 "http://192.168.1.42:1236/settings"
```

#### Configs
All standard from prod + the reverse nginx from dev. Changed only hostname to IP address in lemmy.hjson
##### docker-compose

<details>
  <summary>Click to open</summary>

```
version: '2.2'

services:
  nginx:
    image: nginx:1-alpine
    ports:
      - "1236:1236"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - pictrs
      - lemmy-ui

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  lemmy:
    image: dessalines/lemmy:0.16.4
    ports:
      - "127.0.0.1:8536:8536"
      - "127.0.0.1:6669:6669"
    restart: always
    #environment:
    #  - RUST_LOG="warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"
    environment:
      - RUST_LOG="warn,lemmy_server=debug,lemmy_api=debug,lemmy_api_common=debug,lemmy_api_crud=debug,lemmy_apub=debug,lemmy_db_schema=debug,lemmy_db_views=debug,lemmy_db_views_actor=debug,lemmy_db_views_moderator=debug,lemmy_routes=debug,lemmy_utils=debug,lemmy_websocket=debug"
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs

  lemmy-ui:
    image: dessalines/lemmy-ui:0.16.5
    ports:
      - "127.0.0.1:1235:1234"
    restart: always
    environment:
      - LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_EXTERNAL_HOST=localhost:8536
      - LEMMY_HTTPS=false
      - LEMMY_UI_DEBUG=true
    depends_on:
      - lemmy

  pictrs:
    image: asonix/pictrs:0.3.1
    ports:
      - "127.0.0.1:8537:8080"
      - "127.0.0.1:6670:6669"
    user: 991:991
    environment:
      - RUST_LOG=debug
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always
```

</details>

##### lemmy.hjson

<details>
  <summary>Click to open</summary>

```
{
  # for more info about the config, check out the documentation
  # https://join-lemmy.org/docs/en/administration/configuration.html

  setup: {
    # username for the admin user
    admin_username: "lemmy"
    # password for the admin user
    admin_password: "lemmylemmy"
    # name of the site (can be changed later)
    site_name: "lemmy-test"
  }

  opentelemetry_url: "http://otel:4137"

  # the domain name of your instance (eg "lemmy.ml")
  hostname: "192.168.1.42"
  # address where lemmy should listen for incoming requests
  bind: "0.0.0.0"
  # port where lemmy should listen for incoming requests
  port: 8536
  # settings related to the postgresql database
  pictrs_config: {
    url: "http://pictrs:8080"
    api_key: "API_KEY"
  }
  database: {
    # name of the postgres database for lemmy
    database: "lemmy"
    # username to connect to postgres
    user: "lemmy"
    # password to connect to postgres
    password: "password"
    # host where postgres is running
    host: "postgres"
    # port where postgres can be accessed
    port: 5432
    # maximum number of active sql connections
    pool_size: 5
  }
  slur_filter:
    '''
    (fag(g|got|tard)?\b|cock\s?sucker(s|ing)?|ni((g{2,}|q)+|[gq]{2,})[e3r]+(s|z)?|mudslime?s?|kikes?|\bspi(c|k)s?\b|\bchinks?|gooks?|bitch(es|ing|y)?|whor(es?|ing)|\btr(a|@)nn?(y|ies?)|\b(b|re|r)tard(ed)?s?)
    '''
#  # optional: email sending configuration
#  email: {
#    # hostname and port of the smtp server
#    smtp_server: ""
#    # login name for smtp server
#    smtp_login: ""
#    # password to login to the smtp server
#    smtp_password: ""
#    # address to send emails from, eg "noreply@your-instance.com"
#    smtp_from_address: ""
#    # whether or not smtp connections should use tls
#    use_tls: true
#  }
}
```

</details>

##### nginx.conf

<details>
  <summary>Click to open</summary>

```

worker_processes  1;
events {
    worker_connections  1024;
}
http {
    upstream lemmy {
        server "lemmy:8536";
    }
    upstream lemmy-ui {
        server "lemmy-ui:1234";
    }
    server {
      listen       1236;
      server_name  localhost;

      # frontend
      location / {
        set $proxpass "http://lemmy-ui";
        if ($http_accept = "application/activity+json") {
          set $proxpass "http://lemmy";
        }
        if ($http_accept = "application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"") {
          set $proxpass "http://lemmy";
        }
        if ($request_method = POST) {
          set $proxpass "http://lemmy";
        }
        proxy_pass $proxpass;

        rewrite ^(.+)/+$ $1 permanent;

        # Send actual client IP upstream
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }

      # backend
      location ~ ^/(api|pictrs|feeds|nodeinfo|.well-known) {
        proxy_pass "http://lemmy";
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Add IP forwarding headers
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    }
}
```

</details>

**Comment by Phlogi** [comment]
<img width="402" alt="image" src="https://user-images.githubusercontent.com/6451003/184640758-15c055a4-8c07-4244-9683-8182035c2f3b.png">

I saw this in the response. What does it mean? Where would I enable support for uploading images? Is this a config option?

**Comment by Phlogi** [comment]
Thanks, didn't work. I can confirm that this pull request fixes the issue: https://github.com/LemmyNet/lemmy/pull/2388 Thanks for your fix.

**Comment by Phlogi** [comment]
Config error, this works with dessalines/lemmy:0.16.7-rc.2: 
`  pictrs_url: "http://pictrs:8080"`

No trailing slash!

**Comment by raymand211092** [comment]
Have the same problem, try the solution said by @Phlogi in docker lemmy 0.16.7-rc.2 and it didn't work
Logs container lemmy-lemmy-1

2022-08-26T01:42:31.895561Z  WARN Error encountered while processing the incoming HTTP request: lemmy_server::root_span_builder: images_disabled
   0: lemmy_server::root_span_builder::HTTP request
           with http.method=POST http.scheme="http" [http.host](http://http.host/)=[lemmy.grupotd.nat.cu](http://lemmy.grupotd.nat.cu/) [http.target](http://http.target/)=/pictrs/image otel.kind="server" request_id=e251e106-b10f-43aa-ac48-015612ed5730 http.status_code=400 otel.status_code="OK"
             at src/root_span_[builder.rs:16](http://builder.rs:16/)
LemmyError { message: None, inner: images_disabled, context: "SpanTrace" }
```

**Comment by Phlogi** [comment]
@raymand211092 Post your Lemmy.hjson please

**Comment by raymand211092** [comment]
```
  }
  # Pictrs image server configuration.
  pictrs: {
    # Address where pictrs is available (for image hosting)
    url: "http://pictrs:8080"
    # Set a custom pictrs API key. ( Required for deleting images )
    api_key: "API_KEY"
  }
```

Docker file


```
version: '2.2'

services:
  lemmy:
    image: dessalines/lemmy:0.16.7-rc.2
    ports:
      - "127.0.0.1:8536:8536"
      - "127.0.0.1:6669:6669"
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
 #     - postgres
      - pictrs

  lemmy-ui:
    image: dessalines/lemmy-ui:0.16.5
    ports:
      - "127.0.0.1:1235:1234"
    restart: always
    environment:
      - LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_EXTERNAL_HOST=lemmy.grupotd.nat.cu
      - LEMMY_HTTPS=true
    depends_on: 
      - lemmy

  pictrs:
    image: asonix/pictrs:0.3.1
    ports: 
      - "127.0.0.1:8537:8080"
      - "127.0.0.1:6670:6669"
    user: 991:991
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always
    environment:
#      - PICTRS_OPENTELEMETRY_URL=http://otel:4137
      - PICTRS__API_KEY=string

```
