### ISSUE TITLE
ECONNREFUSED on new instance

### ISSUE THREAD

**Issue by NIXOYE** [LemmyNet/lemmy#2453]
I setup lemmy on a server and after installing everything when i visit the domin all i get is an error that says
`404: FetchError: request to http://lemmy:8536/api/v3/site? failed, reason: connect ECONNREFUSED (ipaddress)`
How do I fix this?

**Comment by dessalines** [comment]
How did you install lemmy?

Post your `lemmy.hjson` and `docker-compose.yml`

**Comment by NIXOYE** [comment]
> How did you install lemmy?

I installed lemmy using the ansible instructions

> Post your `lemmy.hjson` and `docker-compose.yml`

do you mean the config.hsjon? I cant seem to find any file named `lemmy.hjson `and would I still have a `docker-compose.yml` if I installed using ansible?

**Comment by marley77** [comment]
Your "docker-compose.yml"  and "lemmy.hjson" are in /srv/lemmy/[your-domain]. 

To see them, ssh into your server and run `cd /srv/lemmy/[your-domain]`.
---

When I got that 404 error, I had to add these variables to docker-compose.yml, under "lemmy-ui":
 
```
   environment:
      - LEMMY_UI_LEMMY_EXTERNAL_HOST=[your-domain]
      - LEMMY_UI_LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_UI_HTTPS=true
```

Maybe that will work for you.

**Comment by NIXOYE** [comment]
thanks @marley77 i just checked and all those variables are already set.

@dessalines here are my lemmy.hjson and my docker-compse.yml everything in () is stuff i redacted.

lemmy.hjson:

```
{
  # settings related to the postgresql database
  database: {
    # Username to connect to postgres
    user: "(redacted)"
    # Password to connect to postgres
    password: "(redacted)"
    # Host where postgres is running
    host: "postgres"
    # Port where postgres can be accessed
    port: 5432
    # Name of the postgres database for lemmy
    database: "lemmy"
    # Maximum number of active sql connections
    pool_size: 5
  }
  # rate limits for various user actions, by user ip
  rate_limit: {
    # Maximum number of messages created in interval
    message: 180
    # Interval length for message limit, in seconds
    message_per_second: 60
    # Maximum number of posts created in interval
    post: 6
    # Interval length for post limit, in seconds
    post_per_second: 600
    # Maximum number of registrations in interval
    register: 3
    # Interval length for registration limit, in seconds
    register_per_second: 3600
    # Maximum number of image uploads in interval
    image: 6
    # Interval length for image uploads, in seconds
    image_per_second: 3600
    # Maximum number of comments created in interval
    comment: 6
    # Interval length for comment limit, in seconds
    comment_per_second: 600
    search: 60
    # Interval length for search limit, in seconds
    search_per_second: 600
  }
  # Settings related to activitypub federation
  federation: {
    # Whether to enable activitypub federation.
    enabled: true
    # Allows and blocks are described here:
    # https://join-lemmy.org/docs/en/administration/federation_getting_started.html
    #
    # list of instances with which federation is allowed
    allowed_instances: [
      domains.tld
      /* ... */
    ]
    # Instances which we never federate anything with (but previously federated objects are unaffected)
    blocked_instances: [
      string
      /* ... */
    ]
    # If true, only federate with instances on the allowlist and block everything else. If false
    # use allowlist only for remote communities, and posts/comments in local communities
    # (meaning remote communities will show content from arbitrary instances).
    strict_allowlist: true
    # Number of workers for sending outgoing activities. Search logs for Activity queue stats to
    # see information. If running number is consistently close to the worker_count, you should
    # increase it.
    worker_count: 64
  }
  captcha: {
    # Whether captcha is required for signup
    enabled: false
    # Can be easy, medium, or hard
    difficulty: "medium"
  }
  # Email sending configuration. All options except login/password are mandatory
  email: {
    # Hostname and port of the smtp server
    smtp_server: "localhost:25"
    # Login name for smtp server
    smtp_login: "(redacted)"
    # Password to login to the smtp server
    smtp_password: "(redacted)"
    # Address to send emails from, eg noreply@your-instance.com
    smtp_from_address: "(redacted)@(redacted)"
    # Whether or not smtp connections should use tls. Can be none, tls, or starttls
    tls_type: "tls"
  }
  # Parameters for automatic configuration of new instance (only used at first start)
  setup: {
    # Username for the admin user
    admin_username: "(redacted)"
    # Password for the admin user. It must be at least 10 characters.
    admin_password: "(redacted)"
    # Name of the site (can be changed later)
    site_name: "string"
    # Email for the admin user (optional, can be omitted and set later through the website)
    admin_email: "string"
    sidebar: "string"
    description: "string"
    icon: "string"
    banner: "string"
    enable_downvotes: true
    open_registration: false
    enable_nsfw: true
    community_creation_admin_only: true
    require_email_verification: false
    require_application: true
    application_question: "string"
    private_instance: false
    default_theme: "string"
    default_post_listing_type: "string"
  }
  # the domain name of your instance (mandatory)
  hostname: "(domain)"
  # Address where lemmy should listen for incoming requests
  bind: "0.0.0.0"
  # Port where lemmy should listen for incoming requests
  port: 8536
  # Whether the site is available over TLS. Needs to be true for federation to work.
  tls_enabled: true
  # Address where pictrs is available (for image hosting)
  pictrs_url: "http://localhost:8080"
  slur_filter: "(\bThis\b)|(\bis\b)|(\bsample\b)"
  # Maximum length of local community and user names
  actor_name_max_length: 20
  # Maximum number of HTTP requests allowed to handle a single incoming activity (or a single object fetch through the search).
  http_fetch_retry_limit: 25
}

```
docker-compose.yml:

```

services:
  lemmy:
    image: dessalines/lemmy:0.16.7
    ports:
      - "127.0.0.1:5399:8536"
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_queries=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs

  lemmy-ui:
    image: dessalines/lemmy-ui:0.16.7
    ports:
      - "127.0.0.1:19498:1234"
    restart: always
    environment:
      - LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_EXTERNAL_HOST=(domain)
      - LEMMY_HTTPS=true
    volumes:
      - ./volumes/lemmy-ui/extra_themes:/app/extra_themes
    depends_on:
      - lemmy

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=(username)
      - POSTGRES_PASSWORD=(password)
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  pictrs:
    image: asonix/pictrs:0.3.1
    user: 991:991
    ports:
      - "127.0.0.1:13659:8080"
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always
    mem_limit: 200m

  postfix:
    image: mwader/postfix-relay
    environment:
      - POSTFIX_myhostname=(domain)
    restart: "always"

```

btw I couldn't find information on what some of the options do. for example, what does the option of private instance do?
