### ISSUE TITLE
Setting up via Docker guide fails

### ISSUE THREAD

**Issue by hbroer** [LemmyNet/lemmy#2571]
Hi,

i tried to setup a Lemmy instance by following the [docker guide](https://join-lemmy.org/docs/en/administration/install_docker.html). But there are three problems:

1. `wget https://raw.githubusercontent.com/LemmyNet/lemmy/main/docker/lemmy.hjson` does not exist. It is missing the last directory `prod/`
2. `docker-compose up -d` will fail because it is missing a `nginx.conf` - I think you build in the proxy but forgot to update the guide. 
3. There is a error in the `nginx.conf`. It needs to be wrapped with `http {}`.

And now I am stuck. I downloaded the `nginx.config` and changed the vars and fixed the missing wrapping `http{}`. Then docker compose did run, but it is not accesseble and it fails because of the certs. I tried to run letsencrypt manualy on the machine to get the certs and linked the directory. But still does not work. 

I am not very into docker (-compose) so my knowledge here is very basic.

From the Logs:
```
proxy_1     | 2022/11/19 21:57:52 [emerg] 1#1: cannot load certificate "/etc/letsencrypt/live/[[removeddomainname]]/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/[[removeddomainname]]/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

`docker-compose.yml`:
```
services:
  proxy:
    image: nginx:1-alpine
    networks:
      - lemmyinternal
      - lemmyexternalproxy
    ports:
      # only ports facing any connection from outside
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # setup your certbot and letsencrypt config
      - ./letsencrypt:/etc/letsencrypt/live
      - ./certbot:/var/www/certbot
    restart: always
    depends_on:
      - pictrs
      - lemmy-ui
```

I made a symlink `ln -s /etc/letsencrypt/live ./letsencrypt`. I can access the missing file on the machine with `cat /etc/letsencrypt/live/[[removeddomainname]]/fullchain.pem` and `cat ./letsencrypt/[[removeddomainname]]/fullchain.pem`

Can someone update the guide so that I can check what I missed?
