### ISSUE TITLE
Can't access communities from different instances. 

### ISSUE THREAD

**Issue by juliettebee** [LemmyNet/lemmy#2990]
### Issue Summary

Can't access communities from different instances under Docker.

### Steps to Reproduce

1. Use docker compose Lemmy
2. Set up federation 
3. Go to search and put in something like "!linux@lemmy.ml"

### Technical details

- Please post your log: ```
2023-06-09T14:36:45.734309Z ERROR HTTP request{http.method=GET http.scheme="https" http.host=news.juliette.page http.target=/api/v3/ws otel.kind="server" request_id=2efac16b-ad61-4e7e-849b-d77b0501e36a http.status_code=101 otel.status_code="OK"}: lemmy_server::api_routes_websocket: couldnt_find_object: Request error: error sending request for url (https://lemmy.ml/.well-known/webfinger?resource=acct:linux@lemmy.ml): error trying to connect: dns error: failed to lookup address information: Try again
   0: lemmy_apub::fetcher::search::search_query_to_object_id
             at crates/apub/src/fetcher/search.rs:17
   1: lemmy_apub::api::resolve_object::perform
           with self=ResolveObject { q: "!linux@lemmy.ml", auth: Some(Sensitive) }
             at crates/apub/src/api/resolve_object.rs:21
   2: lemmy_server::root_span_builder::HTTP request
           with http.method=GET http.scheme="https" http.host=news.juliette.page http.target=/api/v3/ws otel.kind="server" request_id=2efac16b-ad61-4e7e-849b-d77b0501e36a http.status_code=101 otel.status_code="OK"
             at src/root_span_builder.rs:16
```
- What OS are you trying to install lemmy on? Docker under Debian 11
- Any browser console errors? No

**Comment by dessalines** [comment]
Try these commands to test:

https://join-lemmy.org/docs/en/administration/troubleshooting.html?highlight=feder#federation

Also try pasting the full community url : https://lemmy.ml/c/linux

You have to be logged in for it to work as well.

**Comment by juliettebee** [comment]
Tried everything still getting that error

**Comment by dessalines** [comment]
Can't help unless you give the output of those curl commands.

**Comment by pe1uca** [comment]
I'll work later on this to update the documentation.  

The issue is the lemmy container needs access to the internet, but currently is inside an internal network.  
The fix is to include a 3rd network just for the lemmy container (or include it in the proxy network)  

My current fix is this one:  

```
networks:
  # communication to web and clients
  lemmyexternalproxy:
  lemmybridge:
  # communication between lemmy services
  lemmyinternal:
    driver: bridge
    internal: true
```

And include it in the lemmy container:
```
lemmy:
    image: dessalines/lemmy:0.17.3
    hostname: lemmy
    networks:
      - lemmyinternal
      - lemmybridge
```

The rest of the file can stay as is
