### ISSUE TITLE
[docs/arm64] Installation is possibly missing something

### ISSUE THREAD

**Issue by IngwiePhoenix** [LemmyNet/lemmy#3035]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/lemmy_support .
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Issue Summary

I wanted to install Lemmy on my arm64 maschine. After adjusting the initial setup guide and adding `-linux-arm64` to the tag, after discovering those existed on DockerHub, I was getting a lot of PostgreSQL errors immediately during first-run initialization.

### Steps to Reproduce

I used this `docker-compose.yml` file, derived from the installation guide:

```yaml
version: "3.3"

networks:
  # communication to web and clients
  lemmyexternalproxy:
  # communication between lemmy services
  lemmyinternal:
    driver: bridge
    internal: true

services:
  proxy:
    image: nginx:1-alpine
    networks:
      - lemmyinternal
      - lemmyexternalproxy
    ports:
      # only ports facing any connection from outside
      - 8686:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - pictrs
      - lemmy-ui

  lemmy:
    image: dessalines/lemmy:0.17.3-linux-arm64
    hostname: lemmy
    networks:
      - lemmyinternal
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs

  lemmy-ui:
    image: dessalines/lemmy-ui:0.17.3-linux-arm64
    networks:
      - lemmyinternal
    environment:
      # this needs to match the hostname defined in the lemmy service
      - LEMMY_UI_LEMMY_INTERNAL_HOST=lemmy:8536
      # set the outside hostname here
      - LEMMY_UI_LEMMY_EXTERNAL_HOST=birb.it
      - LEMMY_HTTPS=true
    depends_on:
      - lemmy
    restart: always

  pictrs:
    image: asonix/pictrs:0.3.1
    # this needs to match the pictrs url in lemmy.hjson
    hostname: pictrs
    # we can set options to pictrs like this, here we set max. image size and forced format for conversion
    # entrypoint: /sbin/tini -- /usr/local/bin/pict-rs -p /mnt -m 4 --image-format webp
    networks:
      - lemmyinternal
    environment:
      - PICTRS__API_KEY=***
    user: 991:991
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always

  postgres:
    image: postgres:15-alpine
    # this needs to match the database host in lemmy.hson
    hostname: postgres
    networks:
      - lemmyinternal
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=***
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always
```

The first error that occurs is:
```
postgres_1  | 2023-06-12 07:20:16.146 UTC [59] ERROR:  value too long for type character varying(20)
postgres_1  | 2023-06-12 07:20:16.146 UTC [59] STATEMENT:  INSERT INTO "site" ("name", "sidebar", "updated", "icon", "banner", "description", "actor_id", "last_refreshed_at", "inbox_url", "private_key", "public_key", "instance_id") VALUES ($1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $2, $3, $4, $5, $6, $7) ON CONFLICT ("actor_id") DO UPDATE SET "name" = $8, "actor_id" = $9, "last_refreshed_at" = $10, "inbox_url" = $11, "private_key" = $12, "public_key" = $13, "instance_id" = $14 RETURNING "site"."id", "site"."name", "site"."sidebar", "site"."published", "site"."updated", "site"."icon", "site"."banner", "site"."description", "site"."actor_id", "site"."last_refreshed_at", "site"."inbox_url", "site"."private_key", "site"."public_key", "site"."instance_id"
postgres_1  | 2023-06-12 07:20:16.147 UTC [59] LOG:  could not receive data from client: Connection reset by peer
lemmy_lemmy_1 exited with code 1
```

As you can see, the Lemmy main process imediately exits. Upon restart, it attempts to re-initialize, but runs into duplicate key warnings right away:

```
lemmy_1     | 2023-06-12T07:20:16.940589Z  INFO lemmy_db_schema::utils: Running Database migrations (This may take a long time)...
lemmy_1     | 2023-06-12T07:20:16.944103Z  INFO lemmy_db_schema::utils: Database migrations complete.
lemmy_1     | 2023-06-12T07:20:16.956414Z  INFO lemmy_server::code_migrations: Running user_updates_2020_04_02
lemmy_1     | 2023-06-12T07:20:16.960793Z  INFO lemmy_server::code_migrations: 0 person rows updated.
lemmy_1     | 2023-06-12T07:20:16.961490Z  INFO lemmy_server::code_migrations: Running community_updates_2020_04_02
lemmy_1     | 2023-06-12T07:20:16.963565Z  INFO lemmy_server::code_migrations: 0 community rows updated.
lemmy_1     | 2023-06-12T07:20:16.963795Z  INFO lemmy_server::code_migrations: Running post_updates_2020_04_03
lemmy_1     | 2023-06-12T07:20:16.965443Z  INFO lemmy_server::code_migrations: 0 post rows updated.
lemmy_1     | 2023-06-12T07:20:16.965620Z  INFO lemmy_server::code_migrations: Running comment_updates_2020_04_03
lemmy_1     | 2023-06-12T07:20:16.970107Z  INFO lemmy_server::code_migrations: 0 comment rows updated.
lemmy_1     | 2023-06-12T07:20:16.970718Z  INFO lemmy_server::code_migrations: Running private_message_updates_2020_05_05
lemmy_1     | 2023-06-12T07:20:16.972116Z  INFO lemmy_server::code_migrations: 0 private message rows updated.
lemmy_1     | 2023-06-12T07:20:16.972314Z  INFO lemmy_server::code_migrations: Running post_thumbnail_url_updates_2020_07_27
lemmy_1     | 2023-06-12T07:20:16.973380Z  INFO lemmy_server::code_migrations: 0 Post thumbnail_url rows updated.
lemmy_1     | 2023-06-12T07:20:16.973590Z  INFO lemmy_server::code_migrations: Running apub_columns_2021_02_02
lemmy_1     | 2023-06-12T07:20:16.974674Z  INFO lemmy_server::code_migrations: Running instance_actor_2021_09_29
lemmy_1     | 2023-06-12T07:20:16.983867Z  INFO lemmy_server::code_migrations: Running regenerate_public_keys_2022_07_05
lemmy_1     | 2023-06-12T07:20:16.985912Z  INFO lemmy_server::code_migrations: Running initialize_local_site_2022_10_10
lemmy_1     | 2023-06-12T07:20:16.986756Z  INFO lemmy_server::code_migrations: No Local Site found, creating it.
lemmy_1     | thread 'main' panicked at 'couldnt create local user: DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"local_user_person_id_key\"")', crates/db_schema/src/impls/local_user.rs:157:8
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
postgres_1  | 2023-06-12 07:20:17.403 UTC [61] ERROR:  duplicate key value violates unique constraint "local_user_person_id_key"
postgres_1  | 2023-06-12 07:20:17.403 UTC [61] DETAIL:  Key (person_id)=(2) already exists.
postgres_1  | 2023-06-12 07:20:17.403 UTC [61] STATEMENT:  INSERT INTO "local_user" ("person_id", "password_encrypted", "email", "show_nsfw", "theme", "default_sort_type", "default_listing_type", "interface_language", "show_avatars", "send_notifications_to_email", "show_bot_accounts", "show_scores", "show_read_posts", "show_new_post_notifs", "email_verified", "accepted_application") VALUES ($1, $2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) RETURNING "local_user"."id", "local_user"."person_id", "local_user"."password_encrypted", "local_user"."email", "local_user"."show_nsfw", "local_user"."theme", "local_user"."default_sort_type", "local_user"."default_listing_type", "local_user"."interface_language", "local_user"."show_avatars", "local_user"."send_notifications_to_email", "local_user"."validator_time", "local_user"."show_bot_accounts", "local_user"."show_scores", "local_user"."show_read_posts", "local_user"."show_new_post_notifs", "local_user"."email_verified", "local_user"."accepted_application"
postgres_1  | 2023-06-12 07:20:17.404 UTC [61] LOG:  could not receive data from client: Connection reset by peer
```

And this repeats, indefinitively.

### Technical details

- Please post your log: `sudo docker-compose logs > lemmy_log.out`.
  - See above.
- What OS are you trying to install lemmy on?
  - Ubuntu 22.04 on arm64 via Docker Compose
- Any browser console errors?
  - None, never got there.
