### ISSUE TITLE
No ARM Dockerfile available

### ISSUE THREAD

**Issue by rhld16** [LemmyNet/lemmy#3102]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/lemmy_support .
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Issue Summary

Following the revert of the multi-arch Dockerfile, the Dockerfile.arm file was not readded meaning there's no way to build for arm in the repo. There are also no arm docker images published on Docker Hub for 1.17.4.

### Steps to Reproduce

1. Attempt to build lemmy on an arm machine
2. It fails, so you go look for the old arm Dockerfile

### Technical details

- What OS are you trying to install lemmy on?
Linux CentOS aarch64

**Comment by Nutomic** [comment]
We were having trouble with native ARM builds, so the plan was to cross compile. However that PR ran into problems https://github.com/LemmyNet/lemmy/pull/2806. For now you can install from scratch.

**Comment by samitaaissat** [comment]
From the v0.17.4 branch, I was able to successfully use the docker file in `docker/prod/Dockerfile.arm` to compile it on my M1 MacBook, push it on a private repo, and use it on a server running arm.

So at least this file works

**Comment by NettoHikari** [comment]
Hey, there. Any news on this? Would like to update my instance to 0.18.0, but there are still no dockerfiles available.

**Comment by rhld16** [comment]
@NettoHikari Retrieving the old Dockerfile from the 0.17.4 release still works. #3322 seems to be adding the functionality back as well.

**Comment by paulo-roger** [comment]
Someone with knowledge regarding build lemmy/lemmy-ui on **arm64** could help me please?

I keep getting errors when trying to build lemmy-ui.
This is what I keep getting:

```bash
 => [lemmy_lemmy-ui builder 12/18] RUN yarn --production --prefer-offline                        1.3s
 => ERROR [lemmy_lemmy-ui builder 13/18] RUN yarn build:prod                                     2.7s
------
 > [lemmy_lemmy-ui builder 13/18] RUN yarn build:prod:
#0 0.564 yarn run v1.22.19
#0 0.638 $ yarn clean && node generate_translations.js
#0 0.975 $ yarn run rimraf dist
#0 1.306 $ /usr/src/app/node_modules/.bin/rimraf dist
#0 1.558 $ webpack --mode=production
#0 2.619 [webpack-cli] Failed to load '/usr/src/app/webpack.config.js' config
#0 2.626 [webpack-cli] Error: Cannot find module 'webpack-bundle-analyzer'
#0 2.626 Require stack:
#0 2.626 - /usr/src/app/webpack.config.js
#0 2.626 - /usr/src/app/node_modules/webpack-cli/lib/webpack-cli.js
#0 2.626 - /usr/src/app/node_modules/webpack-cli/lib/bootstrap.js
#0 2.626 - /usr/src/app/node_modules/webpack-cli/bin/cli.js
#0 2.626 - /usr/src/app/node_modules/webpack/bin/webpack.js
#0 2.626     at Module._resolveFilename (node:internal/modules/cjs/loader:1070:15)
#0 2.626     at Module._load (node:internal/modules/cjs/loader:923:27)
#0 2.626     at Module.require (node:internal/modules/cjs/loader:1137:19)
#0 2.626     at require (node:internal/modules/helpers:121:18)
#0 2.626     at Object.<anonymous> (/usr/src/app/webpack.config.js:10:3)
#0 2.626     at Module._compile (node:internal/modules/cjs/loader:1255:14)
#0 2.626     at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
#0 2.626     at Module.load (node:internal/modules/cjs/loader:1113:32)
#0 2.626     at Module._load (node:internal/modules/cjs/loader:960:12)
#0 2.626     at Module.require (node:internal/modules/cjs/loader:1137:19) {
#0 2.626   code: 'MODULE_NOT_FOUND',
#0 2.626   requireStack: [
#0 2.626     '/usr/src/app/webpack.config.js',
#0 2.626     '/usr/src/app/node_modules/webpack-cli/lib/webpack-cli.js',
#0 2.626     '/usr/src/app/node_modules/webpack-cli/lib/bootstrap.js',
#0 2.626     '/usr/src/app/node_modules/webpack-cli/bin/cli.js',
#0 2.626     '/usr/src/app/node_modules/webpack/bin/webpack.js'
#0 2.626   ]
#0 2.626 }
#0 2.649 error Command failed with exit code 2.
#0 2.649 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn build:prod" did not complete successfully: exit code: 2
```

I am using this docker-compose command:

```bash
docker-compose up --build -d
```

It is failing to build lemmy-ui.
this is my lemmi-ui container section of the `docker-compose.yml`

```yml
  lemmy-ui:
    build: ./lemmy-ui
    # image: lemmy-easy-deploy-lemmy-ui
    # image: dessalines/lemmy-ui:0.17.3-linux-arm64
    environment:
      - LEMMY_UI_LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_UI_LEMMY_EXTERNAL_HOST=localhost:1234
      - LEMMY_HTTPS=true
    volumes:
      - ./volumes/lemmy-ui/extra_themes:/app/extra_themes
    depends_on:
      - lemmy
    networks:
      - lemmyinternal
      - lemmybridge
    ports:
      - 1234:1234
    restart: always
    logging: *default-logging
```

I am stuck with this since saturday, any idea is appreciated.
