### ISSUE TITLE
[Bug]: Cannot send email using external SMTP server

### ISSUE THREAD

**Issue by padthaitofuhot** [LemmyNet/lemmy#3348]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Possibly related to #3058, but IMO substantively different.

Can't get **external SMTP relay** working; always get connection refused (socket error 111).  The external SMTP *is reachable* (see Technical Details) from the Lemmy host.

I tried two methods for configuring an external SMTP relay:

* Method 1: edit the `config.hjson` as the documented path for this.
* Method 2: leave `config.hjson` alone and instead configure the postfix-relay container with `docker-compose.yml`.

### Steps to Reproduce

Using password reset form to generate test emails.

* Emails generated from Lemmy must pass through the ProtonMail Bridge, which functions as a typical smart-host in SMTP mode and uses STARTTLS for transport security.
* Despite the documentation stating that nothing within {{}} should be edited, because the ProtonMail Bridge requires the SMTP From: address to match an address on the logged-in user account, I do have to use a specific `smtp_from_address:` value, which we'll say is "mailer@domain.tld".

See scenarios in Technical Details.

## OS

```sh
red@lemmy:~/lemmy-ansible$ uname -a
Linux lemmy 5.15.0-75-generic #82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

## ProtonMail Bridge Connectivity

Connectivity with the protonmail bridge relay works fine from the box on which Lemmy resides.

```
user@lemmy:~/lemmy-ansible$ nc protonmail.bridge.domain.tld 1025
220 127.0.0.1 ESMTP Service Ready
EHLO LEMMY.BOX.DOMAIN.TLD
250-Hello LEMMY.BOX.DOMAIN.TLD
250-PIPELINING
250-8BITMIME
250-ENHANCEDSTATUSCODES
250-CHUNKING
250-STARTTLS
250-AUTH PLAIN LOGIN
250 SIZE
STARTTLS
220 2.0.0 Ready to start TLS
QUIT
550 5.0.0 Handshake error
QUIT
221 2.0.0 Bye
```

### config.hjson
```jsx
{
  # for more info about the config, check out the documentation
  # https://join-lemmy.org/docs/en/administration/configuration.html

  database: {
    host: postgres
    password: "{{ postgres_password }}"
  }
  hostname: "{{ domain }}"
  pictrs: {
    url: "http://pictrs:8080/"
    api_key: "{{ postgres_password }}"
  }
  email: {
    smtp_server: "protonmail.bridge.domain.tld:1025"
    smtp_from_address: "mailer@domain.tld"
    smtp_login: "mailer@domain.tld"
    smtp_password: "REDACTED_PASSWORD"
    tls_type: "starttls"
  }
}
```

### docker-compose.yml
```yaml
  postfix:
    image: mwader/postfix-relay
    environment:
      - POSTFIX_myhostname={{ domain }}
    restart: "always"
    logging: *default-logging
```
### Result

```
lemmy_1     | 2023-06-26T01:42:46.822937Z  WARN Error encountered while processing the incoming HTTP request: lemmy_server::root_span_builder: email_send_failed: Connection error: Connection refused (os error 111)
lemmy_1     |    0: lemmy_api::local_user::reset_password::perform
lemmy_1     |              at crates/api/src/local_user/reset_password.rs:15
lemmy_1     |    1: lemmy_server::root_span_builder::HTTP request
lemmy_1     |            with http.method=POST http.scheme="https" http.host=lemmy.domain.tld http.target=/api/v3/user/password_reset otel.kind="server" request_id=61121d37-e43c-4227-afda-334524b04fb4 http.status_code=400 otel.status_code="OK"
lemmy_1     |              at src/root_span_builder.rs:16
lemmy_1     | LemmyError { message: Some("email_send_failed"), inner: Connection error: Connection refused (os error 111)
lemmy_1     | 
lemmy_1     | Caused by:
lemmy_1     |     Connection refused (os error 111), context: SpanTrace [{ target: "lemmy_api::local_user::reset_password", name: "perform", file: "crates/api/src/local_user/reset_password.rs", line: 15 }, { target: "lemmy_server::root_span_builder", name: "HTTP request", fields: "\u{1b}[3mhttp.method\u{1b}[0m\u{1b}[2m=\u{1b}[0mPOST \u{1b}[3mhttp.scheme\u{1b}[0m\u{1b}[2m=\u{1b}[0m\"https\" \u{1b}[3mhttp.host\u{1b}[0m\u{1b}[2m=\u{1b}[0mlemmy.domain.tld \u{1b}[3mhttp.target\u{1b}[0m\u{1b}[2m=\u{1b}[0m/api/v3/user/password_reset \u{1b}[3motel.kind\u{1b}[0m\u{1b}[2m=\u{1b}[0m\"server\" \u{1b}[3mrequest_id\u{1b}[0m\u{1b}[2m=\u{1b}[0m61121d37-e43c-4227-afda-334524b04fb4 \u{1b}[3mhttp.status_code\u{1b}[0m\u{1b}[2m=\u{1b}[0m400 \u{1b}[3motel.status_code\u{1b}[0m\u{1b}[2m=\u{1b}[0m\"OK\"", file: "src/root_span_builder.rs", line: 16 }] }
lemmy_1     | 2023-06-26T01:42:46.822989Z  INFO actix_web::middleware::logger: 10.0.0.90 'POST /api/v3/user/password_reset HTTP/1.1' 400 29 'https://lemmy.domain.tld/login' 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0' 0.019804    
proxy_1     | 192.168.128.1 - - [26/Jun/2023:01:42:46 +0000] "POST /api/v3/user/password_reset HTTP/1.1" 400 29 "https://lemmy.domain.tld/login" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0"

```
---
### config.hjson
```jsx
{
  # for more info about the config, check out the documentation
  # https://join-lemmy.org/docs/en/administration/configuration.html

  database: {
    host: postgres
    password: "{{ postgres_password }}"
  }
  hostname: "{{ domain }}"
  pictrs: {
    url: "http://pictrs:8080/"
    api_key: "{{ postgres_password }}"
  }
  email: {
    smtp_server: "postfix:25"
    smtp_from_address: "mailer@domain.tld"
    tls_type: "none"
  }
}
```

### docker-compose.yml postfix section
```yaml
  postfix:
    image: mwader/postfix-relay
    environment:
      - POSTFIX_myhostname={{ domain }}
        # Enable auth
      - POSTFIX_smtp_sasl_auth_enable=yes
        # Set username and password
      - POSTFIX_smtp_sasl_password_maps=static:mailer@domain.tld:REDACTED_PASSWORD
      - POSTFIX_smtp_sasl_security_options=oanonymous
        # Turn on tls encryption 
      - POSTFIX_smtp_use_tls=yes
      - POSTFIX_smtp_tls_security_level=may
      - POSTFIX_header_size_limit=4096000
        # Set external SMTP relay host here IP or hostname accepted along with a port number. 
      - POSTFIX_relayhost=[protonmail.bridge.domain.tld]:1025
        # accept email from our web-server only (adjust to match your VPC/VLAN etc)
      - POSTFIX_inet_interfaces=0.0.0.0
    restart: "always"
    logging: *default-logging
```

### Result
```
lemmydomaintld-proxy-1     | 192.168.128.1 - - [26/Jun/2023:01:19:04 +0000] "POST /api/v3/user/password_reset HTTP/1.1" 400 29 "https://lemmy.domain.tld/login" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0"
lemmydomaintld-lemmy-1     | 2023-06-26T01:19:04.849488Z  WARN Error encountered while processing the incoming HTTP request: lemmy_server::root_span_builder: email_send_failed: Connection error: Connection refused (os error 111)
lemmydomaintld-lemmy-1     |    0: lemmy_api::local_user::reset_password::perform
lemmydomaintld-lemmy-1     |              at crates/api/src/local_user/reset_password.rs:15
lemmydomaintld-lemmy-1     |    1: lemmy_server::root_span_builder::HTTP request
lemmydomaintld-lemmy-1     |            with http.method=POST http.scheme="https" http.host=lemmy.domain.tld http.target=/api/v3/user/password_reset otel.kind="server" request_id=5fabe95d-1a90-4fbe-8724-cee85deddb67 http.status_code=400 otel.status_code="OK"
lemmydomaintld-lemmy-1     |              at src/root_span_builder.rs:16
lemmydomaintld-lemmy-1     | LemmyError { message: Some("email_send_failed"), inner: Connection error: Connection refused (os error 111)
lemmydomaintld-lemmy-1     | 
lemmydomaintld-lemmy-1     | Caused by:
lemmydomaintld-lemmy-1     |     Connection refused (os error 111), context: SpanTrace [{ target: "lemmy_api::local_user::reset_password", name: "perform", file: "crates/api/src/local_user/reset_password.rs", line: 15 }, { target: "lemmy_server::root_span_builder", name: "HTTP request", fields: "\u{1b}[3mhttp.method\u{1b}[0m\u{1b}[2m=\u{1b}[0mPOST \u{1b}[3mhttp.scheme\u{1b}[0m\u{1b}[2m=\u{1b}[0m\"https\" \u{1b}[3mhttp.host\u{1b}[0m\u{1b}[2m=\u{1b}[0mlemmy.domain.tld \u{1b}[3mhttp.target\u{1b}[0m\u{1b}[2m=\u{1b}[0m/api/v3/user/password_reset \u{1b}[3motel.kind\u{1b}[0m\u{1b}[2m=\u{1b}[0m\"server\" \u{1b}[3mrequest_id\u{1b}[0m\u{1b}[2m=\u{1b}[0m5fabe95d-1a90-4fbe-8724-cee85deddb67 \u{1b}[3mhttp.status_code\u{1b}[0m\u{1b}[2m=\u{1b}[0m400 \u{1b}[3motel.status_code\u{1b}[0m\u{1b}[2m=\u{1b}[0m\"OK\"", file: "src/root_span_builder.rs", line: 16 }] }
lemmydomaintld-lemmy-1     | 2023-06-26T01:19:04.849549Z  INFO actix_web::middleware::logger: 10.0.0.90 'POST /api/v3/user/password_reset HTTP/1.1' 400 29 'https://lemmy.domain.tld/login' 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0' 0.008813  
```

### Version

BE: 0.18.0
