### ISSUE TITLE
[Bug]: "Origin is not allowed to make this request" despite `Access-Control-Allow-Origin: *`

### ISSUE THREAD

**Issue by NatoBoram** [LemmyNet/lemmy#3481]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When making a GET request (ex `https://lemmy.world/api/v3/site`), if the origin is not the same as the hostname (`lemmy.world`), then we obtain an error.

Headers:

```yaml
HTTP/2 400 Bad Request
server: nginx/1.18.0 (Ubuntu)
date: Tue, 04 Jul 2023 22:12:30 GMT
content-length: 42
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
access-control-allow-origin: *
access-control-allow-methods: GET, POST, PUT, OPTIONS
access-control-allow-headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range
access-control-expose-headers: Content-Length,Content-Range
X-Firefox-Spdy: h2
```

Body:

```
Origin is not allowed to make this request
```

As it stands, it's easy to make a client that works around this bug during SSR, but I'd like to deploy that on mobile devices or on static web servers like GitHub Pages.

### Steps to Reproduce

1. Press F12
2. Click on "Console"
3. Make a `fetch` request to some Lemmy instance

```js
fetch("https://lemmy.world/api/v3/site")
```

### Technical Details

N/A

### Version

BE: 0.18.1-rc.4-11-gcf1c4dd7b

### Lemmy Instance URL

lemmy.world
