### ISSUE TITLE
Question: User-Agent format recommendation for custom clients

### ISSUE THREAD

**Issue by NatoBoram** [LemmyNet/lemmy#3537]
### Question

I'm making a custom client. I want Lemmy instances to be able to recognize my client since it's the polite thing to do.

When I set out to discover good user agent names, I found [this recommendation by Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent): 

```yaml
User-Agent: <product> / <product-version> <comment>
User-Agent: curl/7.64.1
User-Agent: PostmanRuntime/7.26.5
```

So,  great, my app shall now be known as

```yaml
User-Agent: leanish/0.0.0
```

Well, turns out that Lemmy doesn't like that for some reason.

```yaml
HTTP/1.1 403 Forbidden
Access-Control-Allow-Origin: *
content-length: 32
content-type: application/json
Date: Sat, 08 Jul 2023 01:30:07 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Body:
	{"message":"Invalid User-Agent"}
```

That said, if I name it `@natoboram/leanish@0.0.0`, it works.

In any case...

* What are your recommendations for user agent names?
* Should https://github.com/LemmyNet/lemmy-js-client add a `User-Agent` parameter in its constructor?
* Are there plans to track and show user agents to instance administrators?
* Do you actually recommend setting custom user agents or should we just spoof a browser?
