### ISSUE TITLE
[Bug]: 0.19.5 (and 0.19.4) InboxTimeout: InboxTimeout

### ISSUE THREAD

**Issue by AgentScrubbles** [LemmyNet/lemmy#4850]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

After upgrading to 0.19.4 (or 0.19.5) from 0.19.3, I cannot access the UI, it times out.  Checking Lemmy's logs, the following message repeats infinitely:

```
lemmy-1     | 2024-06-19T16:33:34.325525Z  WARN lemmy_server::root_span_builder: InboxTimeout: InboxTimeout
lemmy-1     |    0: lemmy_server::root_span_builder::HTTP request
lemmy-1     |            with http.method=POST http.scheme="https" http.host=<<instancename>> http.target=/inbox otel.kind="server" request_id=f86bfc9e-393c-44ad-adee-3c3f43cdb0e2
lemmy-1     |              at src/root_span_builder.rs:16

```

### Steps to Reproduce

Unfortunately the only steps I have are from the upgrade itself, bumping the versions of the docker images.  I'll add the docker versions below.

The only changes for the upgrade was pictrs from 0.5 to 0.5.16 and both Lemmy and Lemmy-UI to 0.19.4 (and then 5)

```yaml
networks:
  # communication to web and clients
  externalproxy:
  localconnector:
  # communication between lemmy services
  lemmyinternal:
    driver: bridge
      # internal: true

services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - <<redacted>>:/var/www/certbot/:rw
      - <<redacted>>:/etc/letsencrypt/:rw

  proxy:
    image: nginx:1-alpine
    networks:
      - lemmyinternal
      - externalproxy
    ports:
      # only ports facing any connection from outside
      - 80:80 
      - 443:443
    volumes:
      - <<redacted>>:/etc/nginx/nginx.conf:ro
      - <<redacted>>:/etc/nginx/proxy.conf:ro
      - <<redacted>>:/var/www/certbot/:ro
      - <<redacted>>:/etc/nginx/ssl/:ro
      - <<redacted>>:/cert:ro
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    depends_on:
      - pictrs
      - lemmy-ui

  lemmy:
    image: dessalines/lemmy:0.19.5
    hostname: lemmy
    networks:
      - externalproxy
      - lemmyinternal
    restart: always
    environment:
      - RUST_LOG=warn
      # - RUST_LOG="warn,lemmy_server=warn,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=warn"
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs
    deploy:
      resources:
        limits:
          memory: 500M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  lemmy-ui:
    image: dessalines/lemmy-ui:0.19.5
    networks:
      - lemmyinternal
    environment:
      - LEMMY_UI_LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_UI_LEMMY_EXTERNAL_HOST=<<redacted>>
      - LEMMY_HTTPS=true
    depends_on:
      - lemmy
    restart: always
    volumes:
      - ./volumes/lemmy-ui/extra_themes:/app/extra_themes

  pictrs:
    image: asonix/pictrs:0.5.16
    hostname: pictrs
    networks:
      - lemmyinternal
    environment:
      - RUST_BACKTRACE=1
      - PICTRS__STORE__TYPE=object_storage
      - PICTRS__STORE__ENDPOINT=<<redacted>>
      - PICTRS__STORE__BUCKET_NAME=<<redacted>>
      - PICTRS__STORE__REGION=<<redacted>>
      - PICTRS__STORE__ACCESS_KEY=<<redacted>>
      - PICTRS__STORE__SECRET_KEY=<<redacted>>
      - PICTRS__STORE__USE_PATH_STYLE=false
      - PICTRS__API_KEY=API_KEY
      - PICTRS__SERVER__API_KEY=<<redacted>>
    user: 991:991
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always

  postgres:
    image: postgres:16.2-alpine
    # this needs to match the database host in lemmy.hson
    hostname: postgres
    networks:
      - lemmyinternal
    environment:
      - POSTGRES_USER=<<redacted>>
      - POSTGRES_PASSWORD=<<redacted>>
      - POSTGRES_DB=<<redacted>>
    volumes:
      - <<volume>>:/var/lib/postgresql/data
      - <<volume>>:/backups
    restart: always
    deploy:
      resources:
        limits:
          memory: 1500M

```

### Technical Details

```
postgres-1  | 
postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres-1  | 
lemmy-1     | Lemmy v0.19.5
postgres-1  | 2024-06-19 16:32:08.986 UTC [1] LOG:  starting PostgreSQL 16.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
postgres-1  | 2024-06-19 16:32:08.986 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres-1  | 2024-06-19 16:32:08.986 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres-1  | 2024-06-19 16:32:08.993 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-1  | 2024-06-19 16:32:09.010 UTC [25] LOG:  database system was shut down at 2024-06-19 16:31:45 UTC
postgres-1  | 2024-06-19 16:32:09.049 UTC [1] LOG:  database system is ready to accept connections
lemmy-1     | Federation enabled, host is <<host>>
lemmy-1     | Starting HTTP server at 0.0.0.0:8536
lemmy-1     | 2024-06-19T16:32:37.794541Z  WARN lemmy_server::root_span_builder: IncorrectLogin: IncorrectLogin
lemmy-1     |    0: lemmy_server::root_span_builder::HTTP request
lemmy-1     |            with http.method=GET http.scheme="https" http.host=<<host>> http.target=/api/v3/private_message/list otel.kind="server" request_id=44289a0e-cf91-4219-8244-6e8a574e8969
lemmy-1     |              at src/root_span_builder.rs:16
lemmy-1     | 2024-06-19T16:32:44.106053Z  WARN lemmy_server::root_span_builder: Unknown: Domain "discuss.tchncs.de" is blocked
lemmy-1     |    0: lemmy_apub::objects::comment::verify
lemmy-1     |              at crates/apub/src/objects/comment.rs:139
lemmy-1     |    1: lemmy_apub::fetcher::post_or_comment::verify
lemmy-1     |              at crates/apub/src/fetcher/post_or_comment.rs:68
lemmy-1     |    2: lemmy_apub::activity_lists::community
lemmy-1     |              at crates/apub/src/activity_lists.rs:103
lemmy-1     |    3: lemmy_apub::activities::community::announce::receive
lemmy-1     |              at crates/apub/src/activities/community/announce.rs:161
lemmy-1     |    4: lemmy_server::root_span_builder::HTTP request
lemmy-1     |            with http.method=POST http.scheme="https" http.host=<<host>> http.target=/inbox otel.kind="server" request_id=fab1a369-7ffb-4af8-8768-ff43175ef648
lemmy-1     |              at src/root_span_builder.rs:16
lemmy-1     | 2024-06-19T16:32:53.886029Z  WARN lemmy_server::root_span_builder: InboxTimeout: InboxTimeout
lemmy-1     |    0: lemmy_server::root_span_builder::HTTP request
lemmy-1     |            with http.method=POST http.scheme="https" http.host=<<host>> http.target=/inbox otel.kind="server" request_id=40d9c3ee-cb31-4b86-b4c3-8dfaa058a9c3
lemmy-1     |              at src/root_span_builder.rs:16
lemmy-1     | 2024-06-19T16:32:57.904680Z  WARN lemmy_server::root_span_builder: InboxTimeout: InboxTimeout
lemmy-1     |    0: lemmy_server::root_span_builder::HTTP request
lemmy-1     |            with http.method=POST http.scheme="https" http.host=<<host>> http.target=/inbox otel.kind="server" request_id=c7449a12-f730-4e57-9bc3-c64f2d8eb643
lemmy-1     |              at src/root_span_builder.rs:16
lemmy-1     | 2024-06-19T16:32:59.652438Z  WARN lemmy_server::root_span_builder: InboxTimeout: InboxTimeout
lemmy-1     |    0: lemmy_server::root_span_builder::HTTP request
lemmy-1     |            with http.method=POST http.scheme="https" http.host=<<host>> http.target=/inbox otel.kind="server" request_id=0c7754ac-fa41-4673-9f40-00dd349b626b
lemmy-1     |              at src/root_span_builder.rs:16
```

### Version

0.19.4

### Lemmy Instance URL

poptalk.scrubbles.tech
