### ISSUE TITLE
Set front_end_dir via env var in Dockerfile

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#843]
Its unnecessary and confusing to set this in lemmy.hjson in production, because anyway it cant be changed from the default value (`/app/dist`). We might as well set it in Docker, to make things easier.

https://dev.lemmy.ml/docs/administration_configuration.html

**Comment by dessalines** [comment]
I think this one should be closed, its in the config because even outside of docker, someone might want to provide the folder to their own tweaked/alternative front end.

**Comment by Nutomic** [comment]
That wouldnt work with the Docker image, because the frontend path refers to a folder inside the Docker image. So either way you would have to recompile it (or serve the different frontend outside the image, eg via nginx).

**Comment by dessalines** [comment]
Couldn't someone add a volume mount, something like

```
  lemmy:
    image: dessalines/lemmy:v0.7.13
   ...
    volumes:
      - ./lemmy.hjson:/config/config.hjson
      - ./my_front_end_dir:/alt_front_end
```
and lemmy.hjson could contain `front_end_dir: /alt_front_end`
