### ISSUE TITLE
Websockets in local environment

### ISSUE THREAD

**Issue by rfwatson** [LemmyNet/lemmy#855]
:wave:
After following the instructions [here](https://dev.lemmy.ml/docs/contributing_local_development.html) I see a never-ending loading spinner when I visit `localhost:4444`.

Checking dev tools, it looks like there is no websocket connection available on port 8540:

```
Firefox can’t establish a connection to the server at ws://localhost:8540/api/v1/ws.
```
The rust backend is running on port 8536.

Digging into the Docker setup suggests it might be expecting Nginx on this port but I can't find any documentation.

Did I miss something? How can I get a minimal working development environment working?

**Comment by dessalines** [comment]
Sorry, that was when I was doing lots of UI changes for federation testing, I forgot to change it back.

run a `git pull`, I updated the `env.ts` to reference `8536` now when doing the front end testing.

**Comment by dessalines** [comment]
Locally the federation docker runs at 3 different ports, `8540`, `8550`, and `8560`, so you can't really use it for the hot-reload dev anyway. This should be okay now.

**Comment by rfwatson** [comment]
Thanks!

Are you sure you pushed the change you mentioned (last change on env.ts is still fcf1c65fc131478632525ce44a792f1578932f4a as far as I can see) but updating that configuration manually does indeed fix the issue. :pray:

**Comment by dessalines** [comment]
Oops, my bad, this is pushed now 15af11da

**Comment by guysoft** [comment]
Hey,
I am getting a similar issue here on 0.16.7.
Websockets dont work if I go either via the proxy or the docker container directly.

Is there a way to debug this?

**Comment by dessalines** [comment]
How are you installing lemmy?

Post your docker-compose and nginx.conf.

**Comment by guysoft** [comment]
I am using docker-compose and for the reverse proxy I am using Traefik. 
However I am even getting this issue if I do an ssh tunnel directly to the lemmy-ui container.

That is even if I do:
```bash
ssh ubuntu@example.org -L localhost:9999:172.19.0.4:1234
```

And then access the site on using http://localhost:9999 
(where 172.19.0.4 is the IP of the lemmy-ui container)


```yaml
version: "3.3"

services:
  lemmy:
    image: dessalines/lemmy:0.16.7
    hostname: lemmy
    container_name: lemmy
    networks:
      - lemmyinternal
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs

  lemmy-ui:
    image: dessalines/lemmy-ui:0.16.7
    container_name: lemmy-ui
    networks:
      - lemmyinternal
      - default
    environment:
      # this needs to match the hostname defined in the lemmy service
      - LEMMY_INTERNAL_HOST=lemmy:8536
      # set the outside hostname here
      - LEMMY_EXTERNAL_HOST=example.org
      - LEMMY_HTTPS=false
    depends_on:
      - lemmy
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lemmy.rule=Host(`example.org`)"
      - "traefik.http.routers.lemmy.entrypoints=web"
      - "traefik.http.services.lemmy.loadbalancer.server.port=1234"
      - "traefik.docker.network=web"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=http"
      - "traefik.http.services.lemmy.loadbalancer.sticky=true"


  pictrs:
    image: asonix/pictrs:0.3.1
    container_name: lemmy-pictrs
    # this needs to match the pictrs url in lemmy.hjson
    hostname: pictrs
    # we can set options to pictrs like this, here we set max. image size and forced format for conversion
    # entrypoint: /sbin/tini -- /usr/local/bin/pict-rs -p /mnt -m 4 --image-format webp
    networks:
      - lemmyinternal
    environment:
      - PICTRS__API_KEY=API_KEY
    user: 991:991
    volumes:
      - /mnt/docker/lemmy/pictrs:/mnt
    restart: always

  postgres:
    image: postgres:14-alpine
    container_name: lemmy-db
    # this needs to match the database host in lemmy.hson
    hostname: postgres
    networks:
      - lemmyinternal
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=lemmy
      - POSTGRES_DB=lemmy
    volumes:
      - /mnt/docker/lemmy/postgres/data:/var/lib/postgresql/data
    restart: always


networks:
  # communication to web and clients
  default:
    name: web
    external: true
  # communication between lemmy services
  lemmyinternal:
    name: lemmy-internal
    internal: true
```

```hjson
{
  # for more info about the config, check out the documentation
  # https://join-lemmy.org/docs/en/administration/configuration.html
  # only few config options are covered in this example config

  setup: {
    # username for the admin user
    admin_username: "lemmy"
    # password for the admin user
    admin_password: "lemmylemmy"
    # name of the site (can be changed later)
    site_name: "site name"
  }

  # the domain name of your instance (eg "lemmy.ml")
  hostname: "example.org"
  # address where lemmy should listen for incoming requests
  bind: "0.0.0.0"
  # port where lemmy should listen for incoming requests
  port: 8536
  # Whether the site is available over TLS. Needs to be true for federation to work.
  tls_enabled: true

  # pictrs host
  pictrs_url: "http://pictrs:8080"

  # settings related to the postgresql database
  database: {
    # name of the postgres database for lemmy
    database: "lemmy"
    # username to connect to postgres
    user: "lemmy"
    # password to connect to postgres
    password: "lemmy"
    # host where postgres is running
    host: "postgres"
    # port where postgres can be accessed
    port: 5432
    # maximum number of active sql connections
    pool_size: 5
  }
}

```
